source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'bundler'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

group :test do
  gem 'rspec-rails'
end
