# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: search_utilities 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "search_utilities"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Sebastian Johnsson"]
  s.date = "2014-05-27"
  s.description = "Common search methods/helpers extracted from various projects"
  s.email = "sebastian@agiley.se"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "README",
    "Rakefile",
    "VERSION",
    "lib/search_utilities.rb",
    "lib/search_utilities/cookies.rb",
    "lib/search_utilities/railtie.rb",
    "lib/search_utilities/request.rb",
    "lib/search_utilities/search.rb",
    "lib/search_utilities/search_helper.rb",
    "search_utilities.gemspec",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/Agiley/search_utilities"
  s.rubygems_version = "2.2.2"
  s.summary = "Search Utilities used with Thinking Sphinx"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

